version: 2

sources:
    - name: gz_raw_data
      description: Greenweez raw data
      tables:
        - name: raw_gz_product
          description: Greenweez product data
          columns:
            - name: products_id
              tests:
               - unique
        - name: raw_gz_ship
          description: Greenweez shipping data
          columns:
            - name: orders_id
              tests:
                - unique
            - name: shipping_fee
            - name: logcost
            - name: ship_cost
        - name: raw_gz_sales
          columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: foreign key to ship
           - name: pdt_id
             description: foreign key to product
           - name: revenue
             description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
           - name: quantity
             description: the quantity of products purchased for a given order
          description: Greenweez sales data